### PR TITLE
Refactor mongodb definition 

### PR DESCRIPTION
**Pull request by josephholsten**
Quite a bit of cleanup of the mongodb definition, including:
- cleaning up whitespace
- break definition parameters into multiple lines (so diffs are easier to read)
- check mongodb_type at the beginning of the definition, raising a full ArgumentException on error
- extract params and node attributesinto a new_resource object (to more closely model a lwrp)
- update chef used for test-kitchen (required to work with recent apt cookbooks)

I've made sure to verify this passes test-kitchen.

### CODE REVIEW

**Comment by josephholsten** [comment]
@jamesonjlee could you verify this seems reasonable? I made all of these refactorings while attempting a proper solution to #34 (extensible daemon opts).

**Comment by josephholsten** [comment]
Anyone care to take a look at this?

**Comment by jamesonjlee** [comment]
yeah, I'm wrestling with sysconfig, mongo config, and init script right now.  I'll give this a look over.

**Comment by josephholsten** [comment]
@jamesonjlee anything I can help with? I've got to support extra daemon opts for sm's internal branch, so I've got some time I can dedicate.

**Comment by jamesonjlee** [comment]
this looks good, i'll merge it in and stack a few other stuff on it after and do a patch level bump.

**Comment by jamesonjlee** [comment]
I want to merge this in so the LWRP stuff can move in, but this will break _every_ PR outstanding... thoughts?

**Comment by jamesonjlee** [comment]
let's do this.

**Comment by josephholsten** [comment]
+9000. I'll happily help rebase all the useful PRs.

Honestly, I'd rather encourage other folks to contribute than get this in. But I think these improvements will be valuable in the long term, if not necessary.

As for my opinion on all the open PRs:

## progress
- #12 is deprecated in favor of #64 [closed]
- #34 is deprecated in favor of this refactor [closed]
- #43 is reasonable (if a hack) [merged]
- #47 is questionable (I mostly am skeptical of the port math) [closed in favor of #108]
- #64 is reasonable (preferred to #12) [merged](woo mms support... finally?)
- #77 is reasonable [merged]
- #80 is reasonable (requires merge) [merged](i find myself... screwing up these merges continuously)
- #83 is reasonable [closed](keeping the cookbook vanilla as possible from providers)
- #91 is reasonable (though half of it is logging changes) [merged]
- #111 is deprecated in favor of #91 [closed]
- #112 is terrible ;-) [closed]
- #119 is reasonable [merged](the sort would need to be removed or considered when search is moved out)
- #120 is reasonable (requires whitespace changes) [merged](white space fixing soon...)
- #131 is questionable (seems like a better solution exists) [merged](mongos needs a more looking over)
- #133 minor [merged]
- #138 is reasonable [merged]
- #144 is reasonable [merged]

## up for debate
- #65 is reasonable (mine)
- #82 is reasonable (may require a full rewrite)
- #93 needs rework, but worth ripping from
- #96 needs rework, but worth ripping from
- #102 needs rework (should use platform_family)
- #108 is reasonable (mostly whitespace)
- #125 needs rework (much of it was resolved in other patches)
- #136 needs rework (whitespace, unnecessary sh -> bash, &c)
- #142 is reasonable

**Comment by jamesonjlee** [comment]
I took the list and started editing it to put tags on work done. (mainly I am lazy on this list thing)

**Comment by jamesonjlee** [comment]
@josephholsten can you rebase this and I will merge it in for testing.

**Comment by josephholsten** [comment]
I've rebased this so it is ready to merge! I'll start rebase everything else soon.

**Pull request merged**
