### PR TITLE
Switch to using build-essentials cookbook

### LINKED ISSUE #277: 0.16.0 CentOS 6.5 chef_gem[bson_ext] failed if gcc not instaled
I want to install mongodb replicaset on a clean CentOS 6.5
I'm launching it and then get a chef-client error:

```
Gem::Installer::ExtensionBuildError
-----------------------------------
ERROR: Failed to build gem native extension.

        /opt/chef/embedded/bin/ruby extconf.rb
checking for asprintf()... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.
```

I'm making "yum install gcc"
Launching cheif-client and it works all right

### PR DESCRIPTION
**Pull request by wolf31o2**
This is better than maintaining code in this cookbook. Let the guys maintaining `build-essential` deal with distribution-specific issues and such.

Fixes #277

### CODE REVIEW

**Comment by jamesonjlee** [comment]
so I believe the issue was that the mongo gem is needed DURING the compile phase.  This meant that during the initial run, sending any mongo commands via the gem would explode.

The way most people (I) got around this was to include build-essentials in the base cookbook that builds the system before any of these cookbooks ran.

**Comment by wolf31o2** [comment]
The mongo_gem recipe failed for me, missing headers/libs, until I added this. Just GCC is not enough.

**Comment by wolf31o2** [comment]
You'll also notice that this has build-essential installing during the compile phase, so everything is available when the gem is built.

**Comment by dordille** [comment]
I've also been having issues with missing headers that was resolved by applying this patch.

**Comment by duddun** [comment]
Makes sense.

**Comment by wolf31o2** [comment]
Updated from master, so it'll merge cleanly.

**Pull request closed without merging**
