### PR TITLE
Keyfile and arbiter support

### PR DESCRIPTION
**Pull request by lackac**
I've recreated the #20 pull request without whitespace changes. Still, some of these changes are opinionated, and I don't expect you to pull all of it. This is how we have used your cookbook though, and the changes might be useful for someone else too.

### CODE REVIEW

**Comment by dcrosta** [comment]
I'm confused by d00778abfe47ebd83b3aae0d3c33ea11b28ae7dc -- your commit comment says that using `[]` doesn't work in some cases. Can you elaborate on those cases?

**Comment by lackac** [comment]
Sorry, but this was a long time ago and I don't remember the details.

**Comment by dcrosta** [comment]
If you can't say why we need to change node item access to attribute access, then we shouldn't make such a sweeping change. Would you mind re-issuing this once more with _just_ the changes for keyfile? (Arbiter support should also be a separate pull request). Sorry to be a pain about this, just want to keep the history clean.

**Comment by lackac** [comment]
Just cherry-pick the ones you want to include.

**Comment by addisonj** [comment]
@dcrosta if one were to clean this up (get rid of attribute access) and and submit different pull requests, would you accept? at least the arbiter part?

**Comment by dcrosta** [comment]
@addisonj Yes, especially if it were broken into two pull requests (one for keyfile, one for arbiter) -- this is to keep the repo history clean.

**Pull request closed without merging**
