### PR TITLE
first pass at optional logrotate configuration

### PR DESCRIPTION
**Pull request by jspiewak**

### CODE REVIEW

**Comment by jamesonjlee** [comment]
I am closing this PR because this is a business logic that should stay with your private cookbook and not with the general community cb.

**Comment by josephholsten** [comment]
I think this would be great as documentation though, it takes quite a bit of hunting to find the right `postrotate` command.

But if we did add this, we'd eventually have to expose the `frequency`, `rotate`, and `options` attributes. It'll be easier in the long run to document how to do it in a wrapper cookbook.

**Comment by jspiewak** [comment]
I am not sure I agree that this is business logic.
I do agree that it needs to be more configurable, hence saying it was a first pass.
The nice bit about adding it to the definition is that the logrotate configuration gets created for each service.

**Comment by jamesonjlee** [comment]
I call it business logic because some may prefer to use a different solution then logrotate (don't ask me who).  I agree with @josephholsten that this is one of the things that should be added into a documentation/example cookbook that we (will) sorely need.

**Comment by josephholsten** [comment]
Oh, I forgot time mention that we don't use logrotate any more since we switched to syslog. It's also quite reasonable to use stdout logging with upstart console log, systemd journal, runit svlog or a FIFO to a log shipper like lumberjack. 

## 

http://josephholsten.com

**Comment by jspiewak** [comment]
I don't disagree that there are other logging options.

But it would be great if folks who use the stock community cookbook didn't find themselves one month down the road with a 1G mongodb.log and only then realize that having logrotate in place would have been really nice.

The pull request doesn't force one to use logrotate. Just makes it easier out of the box.

@josephholsten how are you configuring syslog with this cookbook?

Anyway, feel free to use this as the basis for documentation around logging.

**Comment by josephholsten** [comment]
@jspiewak sadly, I'm running an old internal fork, which is how I'm doing syslog. But it should be as easy as setting this attribute:

``` ruby
default['mongodb']['config']['syslog'] = true
```

Which would be another thing I'd like to include in this doc improvement.

**Pull request closed without merging**
