### PR TITLE
Chef 11 changes

### PR DESCRIPTION
**Pull request by gilles**
http://docs.opscode.com/breaking_changes_chef_11.html#single-notifies-for-notification

In Chef 11 you can't put multiple notifications in a single call to notify.

Thanks

### CODE REVIEW

**Comment by ericchaves** [comment]
+1 for this pull request.

**Comment by miklernout** [comment]
+1 for this pull...

**Comment by Findekano** [comment]
+1 for this pull!

**Comment by josephholsten** [comment]
Why is this patch so huge? Most of these changes are entirely unrelated to the issue at hand.

**Comment by gilles** [comment]
Ah, seems @dkoepke included the fixes for the parse changes (be carefull with #96 it's broken in multiple ways).

I can open a new one with just the chef11 changes.

**Comment by dkoepke** [comment]
Oops. Didn't realize there was a PR on master. :confused:

**Comment by gilles** [comment]
I'm going to close this one. If you want the chef11 copy this https://github.com/kwarter-cookbooks/mongodb/commit/1c055e4cd5da9e3c03fb3f554748379f0e083a66

**Pull request closed without merging**
