### PR TITLE
add support for mms-agent

### PR DESCRIPTION
**Pull request by nathenharvey**
This pull request adds support for the MongoDB Monitoring Service that was recently announced by 10gen.

https://mms.10gen.com/

Thanks,
Nathen

### CODE REVIEW

**Comment by thekorn** [comment]
Hi Nathen,
thank you for your work on adding mms-agent support to the cookbook, much appreciated.
The diff is huge, so I will have a closer look at it until mid this week, but one question: why did you add all these files to the cookbook itself? Isn't  there any central release place (tarball, repository, etc.) which could be used. Using such a central place would simplify maintainance of the cookbook ;)

Markus

**Comment by nathenharvey** [comment]
Markus,

Thanks, it looks like there is a place to grab those files now - 
https://mms.10gen.com/settings/10gen-mms-agent.zip

I think that may be a recent addition since the service is so new.  Of 
course, I may have overlooked that when I first started using it, too ;)

I'll work on incorporating that into the cookbook and update my pull 
request.  Probably in a day or two.

-Nathen

**Comment by kzk** [comment]
I've written the recipe for mms-agent setup.

> https://github.com/treasure-data/chef-mms-agent

This downloads the zip, and rewrite the settings.py. Hope this will help. MMS is really nice, this is the base line for all MongoDB deployments :-)

**Comment by dcrosta** [comment]
I also have a recipe, in rough shape, for MMS agent installation. I'll see if I can find some time this weekend or next to refactor it as a pull req against this repository.

**Comment by josephholsten** [comment]
@nathenharvey, @kzk, @dcrosta: Have you had a chance to do this? Or should this get a fresh look?

**Comment by dcrosta** [comment]
@kzk I like your approach. Would you be willing to reformulate it as a pull request?

It might also be worth disabling automatic updates (`autoUpdateEnabled`), as that has the potential to interfere with the customizations to the settings.py file that you've made.

**Comment by josephholsten** [comment]
Update: @kzk's chef-mms-agent repo moved to here: https://github.com/treasure-data/chef-mongodb-mms-agent

**Comment by josephholsten** [comment]
I've imported @kzk's mms agent cb here: https://github.com/edelight/chef-mongodb/pull/64

And while I've done the work, I'm not in love with a few things that it does:
- `remote_file` destination of '/tmp/10gen-mms-agent.zip', probably should be rewritten to use ark, or at least `Chef::Config['file_cache_path']` and a checksum.
- gsubing `settings.py` is almost certainly not the Right Thing.
- does this thing come with an init script? regardless, runit should have alternatives.

**Comment by josephholsten** [comment]
What's the status on this PR? Any reason not to merge?

**Comment by jamesonjlee** [comment]
@josephholsten does #64 supercede this PR?

**Comment by josephholsten** [comment]
It is supposed to, yes. But I'd rather wait until I get a patch in for #114, and also replace the runit service with something portable.

**Comment by josephholsten** [comment]
Scratch that. I'd be happy getting #64 in.

**Comment by jamesonjlee** [comment]
closing for #64

**Pull request closed without merging**
