### PR TITLE
Extract shared code from default

### PR DESCRIPTION
**Pull request by josephholsten**
rebase of #82

### CODE REVIEW

**Comment by josephholsten** [comment]
I'm still waiting to see if it passes test-kitchen, but this should get the point across.

**Comment by josephholsten** [comment]
um, this doesn't pass on ubuntu 10.04. Something wrong with upstart:

```
vagrant@default-10gen-ubuntu-1004:~$ /etc/init.d/mongodb restart
Rather than invoking init scripts through /etc/init.d, use the service(8)
utility, e.g. service mongodb restart

Since the script you are attempting to invoke has been converted to an
Upstart job, you may also use the restart(8) utility, e.g. restart mongodb
start: Unable to connect to system bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
```

Does anyone know that master works correctly on ubuntu 10.04?

**Comment by jamesonjlee** [comment]
that because the system is sysvinit to start what should be an upstart file (the message should actually error?).  I saw this when moving from upstart -> init.d in testing (which is not supported)

**Comment by josephholsten** [comment]
well having confirmed this works in master, I'll see if I can spot the diff.

**Comment by josephholsten** [comment]
rebased onto master

**Comment by josephholsten** [comment]
hmm, I can't reproduce the issue any more. Everything is passing in TK. If you can confirm, I think it's ready to merge.

**Pull request merged**
