### PR TITLE
Fixes to allow mongos to start up

### PR DESCRIPTION
**Pull request by jspiewak**
- mongos will not start with dbpath
- mongos requires configdb
- stop including the default recipe as that configures mongodb, which you typically do not want on application host with a local mongos

### CODE REVIEW

**Comment by josephholsten** [comment]
awesome, I was just trying to get an integration test for mongos set up.

**Comment by josephholsten** [comment]
ooo, removing `require "mongodb::default"` means we can remove the `unless configured_as_replicaset` stuff from `recipes/default.rb`

**Comment by josephholsten** [comment]
oh, your `mongodb.config.configdb` explains #196

**Comment by josephholsten** [comment]
@jspiewak could you also review #213?

**Comment by josephholsten** [comment]
@jspiewak reviewing #213 in detail, it looks like your implementation is much cleaner. But I notice that it removes many more config values:

``` ruby
 %w(dbpath nojournal rest smallfiles oplogSize replSet).each { |k| node.default['mongodb']['config'].delete(k) }
```

Can we `mongos` run properly with these? Or should we delete them also?

**Comment by josephholsten** [comment]
Since I've got the configserver integration test (#208) working, I'll try to get an integration test set up for this.

**Comment by jamesonjlee** [comment]
I believe the `mongodb::default` was original due to gem installation issues (I believe this was fixed in chef and in the cookbook), so I think we can (safely?) remove it.  Only case I can see this breaking is if someone is running only the definitions without doing include.

I am generally against edit/changing node attributes outside of the attributes (also there is no guarantee this propagates well).  Instead of deleting, a wrapper should set the field to `nil`.

If I set `node['mongodb']['config']['configsrv']` and this ran, the value I explicitly set would be something different, which is the type(s) of cases I would like to avoid.

(I am not as familiar with the config file anymore, and I am wondering if we should add a explicit 'these values are not accepted for these instance types' into the attributes) instead of doing these case-by-case stuff.

**Comment by jspiewak** [comment]
@josephholsten I made the comment in #213, but I will repeat here.

The reason to remove the other config values is to suppress warnings on startup, but that applies equally to mongod as well as mongos:

```
vagrant@shard1-mongodb01:~$ sudo cat /var/log/upstart/mongodb.log 
warning: remove or comment out this line by starting it with '#', skipping now : fork = false
warning: remove or comment out this line by starting it with '#', skipping now : nojournal = false
warning: remove or comment out this line by starting it with '#', skipping now : smallfiles = false
warning: bind_ip of 0.0.0.0 is unnecessary; listens on all ips by default
```

mongos should be able to run without them. I am not sure if "rest" is an option that would work for mongos, but if it does it should be left.

I would prefer to tackle the suppression of the warnings separately.

I will update the PR to allow for explicitly setting `node[:mongodb][:config][:configsrv]`.

As a strategy, can we have this PR merged, and then circle back to address the editing of node attributes outside of the attributes file?

**Comment by jspiewak** [comment]
BTW, re: gem installation, any thoughts on also installing the bson_ext gem for configuring shards and replicate sets? It would eliminate this warning:

```
[2014-01-27T16:11:50+00:00] INFO: Processing ruby_block[config_replicaset] action create (mongodb::shard line 193)
      ** Notice: The native BSON extension was not loaded. **

      For optimal performance, use of the BSON extension is recommended.

      To enable the extension make sure ENV['BSON_EXT_DISABLED'] is not set
      and run the following command:

        gem install bson_ext

      If you continue to receive this message after installing, make sure that
      the bson_ext gem is in your load path.
```

**Comment by jamesonjlee** [comment]
@jspiewak looks better, i'll merge and test.

**Pull request merged**
