### PR TITLE
Cannot override default config values with nil

### PR DESCRIPTION
**Pull request by josephholsten**
Unfortunately, due to https://github.com/opscode/chef/issues/1507, users cannot accomplish things like #288 & #289. 

By comparing [our default config entries](https://github.com/edelight/chef-mongodb/blob/master/attributes/dbconfig.rb) with [mongo's default entries](http://docs.mongodb.org/v2.4/reference/configuration-options/), shows that `logpath` is the only entry we set which will be unable to be unset entirely. Every other entry we set has a default value provided by mongo, so unsetting can be approximated by an explicit set to that default.

Our available options include:
1. to check for the `syslog` entry, which would unset `logpath`. If a user actually wants to replicate the behaviour of unsetting `logpath` (without setting `syslog`), the user may use a value of `/dev/null`.
2. to stop providing a default logpath in code, perhaps just documenting it in the readme
3. to accept a non `nil` form of nil. This can't be `false`, though it could concievably be `""` or `0`. I'd probably just go with `"nil"` if we needed this.

Considering this range of risk, I suggest we implement option 1: syslog check. I'd personally prefer 2: nil default, but it is incompatible and I can't think of a way to safely mark it as deprecated.

Any objections to syslog check?

### CODE REVIEW

**Comment by jamesonjlee** [comment]
~~if we use `.to_hash` and then `value.nil?` test we should be able to circumvent this issue though?~~
being dumb, yes we should provide a working-work-around.

**Comment by josephholsten** [comment]
The alternatives are
- to stop providing a default logpath in code, perhaps just documenting it in the readme
- to accept a non `nil` form of nil. This can't be `false`, though it could concievably be `""` or `0`. I'd probably just go with `"nil"` if we needed this.

**Comment by josephholsten** [comment]
@hatchetation I'd appreciate your take on these options for our business needs, and @jamesonjlee your take on the best option for maintenance.

Personally, I feel that syslog beats the pants off the file logging implementation that ships with mongo. I'd love to encourage everyone to just use it. But I understand that official and distro packages ship with file logging enabled by default, and our default has reflected that default. Yet I've been opposed to that sort of default since 1998.

**Comment by jamesonjlee** [comment]
I believe `false`, `0` are not compatible but empty string should be (due to the way mongo2.4 handled config files), since the configuration is generated we could just have it skip `''` and put special catches for things (like logpath) into a `mongo-config-helpers.rb` for maintainability.

**Comment by josephholsten** [comment]
@jamesonjlee this should fix the logpath vs syslog issue as well as ensure entries do not render if their value is `''`.

Anything else we should handle?

**Comment by jamesonjlee** [comment]
lgtm.

**Pull request merged**
