### PR TITLE
Add support for configuring `mongod` settings

### PR DESCRIPTION
**Pull request by chapmajs**
This PR adds support for modifying `mongod` settings. We needed to control the contents of `/etc/mongod.conf` for a project and found this cookbook did not support the configurability we needed. Defaults were sourced from the default `/etc/mongod.conf` created after an install on Ubuntu 14.04 AMD64.

### CODE REVIEW

**Comment by chapmajs** [comment]
I wanted to leave the commits expanded out, but I can smash them down after everyone has taken a look.

**Comment by chapmajs** [comment]
Any problems with this PR? Happy to make changes as needed!

**Comment by cjhubert** [comment]
I may just be misunderstanding, but does the recipe not currently do this? For instance on Ubuntu, my `/etc/default/mongodb` file has the line `CONFIGFILE="mongodb.conf"` which tells mongo to read the .conf file at `/mongodb.conf` which has the following:

``` ini
#
# Automatically Generated by Chef, do not edit directly!
#

auth = true
bind_ip = 0.0.0.0
dbpath = /var/lib/mongodb
fork = false
keyFile = /etc/mongodb.key
logappend = true
logpath = /var/log/mongodb/mongodb.log
nojournal = false
port = 27017
replSet = rs_default
rest = false
smallfiles = false
```

I also have an `/etc/mongod.conf` file that was generated, but I think mongo ignores that since it isn't set to read it.

**Comment by chapmajs** [comment]
Not a MongoDB expert, but setting `bind_ip` in `/etc/mongodb.conf` had no effect. MongoDB still bound to Localhost only.

**Comment by cjhubert** [comment]
This sounds familiar, I think I had this problem too, for me, it turned out Mongo wasn't reading the correct file generated by this cookbook. For Ubuntu, I had to set these two settings in the Chef json in order for it to read the right file:

```
"default_init_name": "mongod",
"dbconfig_file": "mongodb.conf",
```

**Comment by chapmajs** [comment]
I haven't tested your solution yet, but if that's the case, shouldn't this cookbook automatically place the correct file and/or ensure MongoDB is reading from the config it's generating?

After a look through the MongoDB source, it seems that the official packages ship with `mongod.conf` but it's completely unclear from their documentation as to which filename they expect you to use. So maybe it's best to specify the filename to MongoDB anyway and remove any ambiguity from the cookbook.

**Comment by cjhubert** [comment]
I _think_ the problem is from a [Mongo 2.6 change](http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/). "The package structure and names have changed as of version 2.6. For instructions on installation of an older release, please refer to the documentation for the appropriate version."

I think it's definitely a challenge maintaining a cookbook for something to run on multiple platforms / version with multiple versions of the application. If this was the problem, sorry for any confusion.

**Comment by chapmajs** [comment]
Haven't abandoned this, just very busy!

I dug back in yesterday, and it seems this is a result of the Debian package installing its own Upstart script, called `mongod`, which is being started immediately after the package installs. Looking into how to best handle this.

Another side-effect is that you end up with two sets of configuration files, Upstart scripts, defaults, et c. Should this cookbook remove the defaults that come with the package? It would have made debugging less confusing.

**Comment by chapmajs** [comment]
To make this more interesting, even if you prevent the package from starting `mongod` when it's finished, the Upstart file is still in place, so it tries to start on reboot.

**Comment by chapmajs** [comment]
Looks like you can get this recipe to overwrite the `mongod` configs with `mongodb_instance "mongod"` in your recipe, but for some reason it's still not restarting properly on Ubuntu.

**Comment by chapmajs** [comment]
OK, so this turned out to be a problem with Ubuntu when using Upstart and MongoDB > 2.6. I've submitted PR #371 to fix the defaults and eliminate duplicate configuration files. This PR is effectively obsoleted by #371

**Pull request closed without merging**
