### PR TITLE
Use immediately... for issue #342

### PR DESCRIPTION
**Pull request by wolf31o2**
This should resolve the third issue reported in #342

### CODE REVIEW

**Comment by samartioli** [comment]
Any idea when the next release will be generated?

**Comment by jamesonjlee** [comment]
i'll roll out 0.16.2 tonight, and push dev to 0.16.3... tonight?

**Comment by samartioli** [comment]
Doesn't look 0.16.2  is picked up  in the supermarket: https://supermarket.getchef.com/cookbooks?utf8=%E2%9C%93&q=mongodb

Does anything else need to be done for that to happen?

**Comment by jamesonjlee** [comment]
uploaded

**Pull request merged**
