### PR TITLE
Fix initial install configuration, and configuration by attributes

### PR DESCRIPTION
**Pull request by jamesonjlee**
- Initial installation is now fixed (and also provides a distro -> 10gen upgrade path for debian, centos)
- configuration is now done with attributes (see dbconfig.rb and sysconfig.rb)
- make it easier to pull down/upgrade the init scripts.

I believe this isn't completely compatible with mongos (yet)

### CODE REVIEW

**Comment by jamesonjlee** [comment]
this should address PRs: #156 #136 parts from #82 #102
this should also address problems highlighted in issues: #70 #88, #92, #118, #146

**Comment by xcoderzach** [comment]
This is awesome, any idea when it'll be ready to try out?

**Comment by jamesonjlee** [comment]
@xcoderzach hopefully I will get it merged this week and start the last unstable version before 1.0

**Comment by xcoderzach** [comment]
awesome, can't wait!

**Comment by st-h** [comment]
this seems to break the upstart script in ubuntu

cat /var/log/upstart/mongodb.log:
start-stop-daemon: need at least one of --exec, --pidfile, --user or --name
Try 'start-stop-daemon --help' for more information.

I don't have much experience writing upstart scripts, but it seems to me that these variable are not initalized in debian-mongodb.upstart.erb: DAEMON, DAEMON_OPTS, DAEMON_USER

**Comment by jamesonjlee** [comment]
@st-h thanks, I found the issue and fixed it

**Pull request merged**
