### PR TITLE
Variablize templates

### PR DESCRIPTION
**Pull request by josephholsten**
having a template pull from node-wide attributes prevents a definition or resource from being used to create multiple different mongodb instances.

### CODE REVIEW

**Comment by jamesonjlee** [comment]
:\ why can't I click merge

**Comment by josephholsten** [comment]
there was a merge conflict. I've rebased.

**Comment by jamesonjlee** [comment]
I did a follow-up commit that made the `variables` calls to be rockets.

**Comment by josephholsten** [comment]
ah, I guess I should test things under ruby 1.8 then.

**Comment by jamesonjlee** [comment]
for now? since we are supporting chef10 still.

**Comment by jhsubscribe** [comment]
Can I please ask for clarification.  Do the rows below "# TODO(jh): parameterize so we can make a resource provider" need to be changed to parameters (like "new_resource.dbpath") before we will be able to use this cookbook to run multiple instances (e.g. mongos, 2x mongod, 3xconfig) on a single VM.

I'm just a little confused because Josephs initial description on this page seems to describe the problem but I can't see that the code update has fixed it.   Apologies if way off the path, I'm relatively new to Chef.

**Comment by jamesonjlee** [comment]
@jhsubscribe the intention is to use the new_resource style to move the definition into a Resource. (Large chunk of this has been done in another one of WIP from @josephholsten)

This may open us up to being able to support multiple instances on a single VM.

**Comment by josephholsten** [comment]
These changes parametrized the sub resources we depend on, but still pull those values from system-wide node attributes. Exposing all of the params that may change is required to support multiple instances running at the same time. 

## 

http://josephholsten.com

**Pull request merged**
