### PR TITLE
Working in the kitchen

### PR DESCRIPTION
**Pull request by jspiewak**

### CODE REVIEW

**Comment by jamesonjlee** [comment]
are the box_urls invalid now? those are suppose to source the bento boxes.

**Comment by jspiewak** [comment]
The [kitchen-vagrant](https://github.com/test-kitchen/kitchen-vagrant/) doc indicates that it will expand the name into the box_url that uses the bento boxes. So it is redundant unless we want to specify something else.

**Comment by jamesonjlee** [comment]
do we need to bump our kitchen-vagrant for that? I don't recall that support before.

otherwise lgtm.

**Comment by jspiewak** [comment]
We are using 0.14, and it looks like this was added in 0.13

**Pull request merged**
