### PR TITLE
Add guard to prevent systemctl usage on amazon.

### LINKED ISSUE #358: Amazon AWS issues
I am learning AWS OpsWorks and trying to deploy a single mongodb instance via OpsWorks.
On the way I had problems using the mongodb recipe with both Amazon Linux 2014.09 and Ubuntu 14.04.
## Ubuntu 14.04

The default mongo config file is is `/etc/mongodb.conf` while ubuntu actually uses `/etc/monod.conf`.
So any custom mongo settings are not applied.

The solution seems to be (I didn't actually verify this) to change [:mongodb][:dbconfig_file] setting from '/etc/mongodb.conf' to '/etc/mongod.conf'.
And I think this should be fixed or mentioned in documentation.
## Amazon Linux 2014.09

Here there is a problem with changing the default db settings using the approach described in the readme.
The following code leads to the deployment error:

```
mongodb_instance "mongodb" do
  bind_ip "127.0.0.1,#{node[:opsworks][:instance][:private_ip]}"
end
```

And the error is:

```
[2014-12-18T20:35:10+00:00] INFO: template[/etc/init.d/mongod] sending run action to execute[mongodb-systemctl-daemon-reload] (immediate)
[2014-12-18T20:35:10+00:00] INFO: Processing execute[mongodb-systemctl-daemon-reload] action run (mongodb-singlenode::default line 174)

================================================================================
Error executing action `run` on resource 'execute[mongodb-systemctl-daemon-reload]'
================================================================================

Errno::ENOENT
-------------
No such file or directory - systemctl

Resource Declaration:
---------------------
# In /var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb/definitions/mongodb.rb

174:   execute 'mongodb-systemctl-daemon-reload' do
175:     command 'systemctl daemon-reload'
176:     action :nothing
177:   end
178: 

Compiled Resource:
------------------
# Declared in /var/lib/aws/opsworks/cache.stage2/cookbooks/mongodb/definitions/mongodb.rb:174:in `block in from_file'

execute("mongodb-systemctl-daemon-reload") do
params {:mongodb_type=>"mongod", :action=>[:enable, :start], :logpath=>"/var/log/mongodb/mongodb.log", :dbpath=>"/data", :configservers=>[], :replicaset=>nil, :notifies=>[], :bind_ip=>"127.0.0.1,172.31.45.215", :name=>"mongod"}
action [:nothing]
retries 0
retry_delay 2
command "systemctl daemon-reload"
backup 5
returns 0
cookbook_name "mongodb-singlenode"
recipe_name "default"
end
```

Here it seems like there is some OS-level incompatibility and Amazon Linux does not have systemctl.
The solution was to avoid this restart - I had to set the bind_ip before including the recipe:

```
node.normal[:mongodb][:config][:bind_ip] = "127.0.0.1,#{node[:opsworks][:instance][:private_ip]}"

include_recipe "mongodb::default"
```

And one more issue with Amazon Linux is that it shows the following warning during the deploy:

```
[2014-12-18T21:23:48+00:00] WARN: CentOS doesn't provide mongodb, forcing use of mongodb-org repo
[2014-12-18T21:23:48+00:00] WARN: 10gen_repo is deprecated, use mongodb_org_repo
```

Sorry for posting multiple problems as a single issue, I just not sure if these are actual problems or this is just me doing something wrong.

### PR DESCRIPTION
**Pull request by miguelcnf**
Should partially fix #358.

### CODE REVIEW

**Comment by Z3r0Sum** [comment]
@miguelcnf Are you still working on this?

+1

**Comment by miguelcnf** [comment]
@Z3r0Sum not really, this was a one time fix and we've been using it from our fork ever since.

The build is actually failing due to a gem dependency on ruby 1.9.3 and not from my change per se.

**Comment by Z3r0Sum** [comment]
@miguelcnf Looks like the project moved: https://github.com/chef-brigade/mongodb-cookbook and has your PR merged there.

**Comment by miguelcnf** [comment]
yea sounds legit ;)

**Pull request closed without merging**
