### PR TITLE
Allow for single member replica sets in chef-server mode, force sharding configuration in mongos recipe

### PR DESCRIPTION
**Pull request by esmet**

### CODE REVIEW

**Comment by jamesonjlee** [comment]
this mean search() didn't return this node as part of a replicaset?

**Comment by esmet** [comment]
Seems that way. I have been using this recipe during bootstrap so maybe the node is not saved to the chef server by the time we execute that code.

**Comment by jamesonjlee** [comment]
does mongos need to get reconfigured as a shard? I feel like that's going to have weird side effect.

**Comment by esmet** [comment]
I used that patch to force a chef-client run on a mongos node to add any new shards that were provisioned using the mongodb::shard recipe. Without it, I couldn't get config_sharding to run without destroying the mongos node in some way (remove a config file, for example) 

Maybe I did something wrong, though.

**Comment by esmet** [comment]
I think I'm going to add a recipe for configuring sharding that does not involve configuring mongos. This way, any existing server can run said recipe to add new shards to the system, and we won't have to force a reconfig in the mongos recipe. Does this sound like the right approach?

**Comment by jspiewak** [comment]
Should we look into an explicit `node.save` at some point before any searches are performed?

How can you configure a shard without having a mongos running?

**Comment by esmet** [comment]
You would need to run it on a node that already has run the mongos recipe. That's probably brittle though. I bet the right thing to do is just get a configure round going without stopping/restarting the mongos (which I think happens now if you re-run the mongos recipe).

Also, yes, saving the node to the server before doing the search makes sense, as it would obviate the need to special case a search returning 0 results.

**Comment by josephholsten** [comment]
Could someone doc exactly what use case this is resolving? Is it for bootstrapping a mongos node? How exactly could I replicate the pain this is solving? Could you provide a sample runlist + attributes?

**Comment by josephholsten** [comment]
this is relevant to changes in #221

**Comment by jamesonjlee** [comment]
This is because in certain environments (say 3 nodes coming up all at once) all the first nodes could end at a state where they can't find each other (and hence members.length == 0).  The change in the definition seems to be forcibly kicking the shard_config twice to make them find each other.

The error should still happen if Chef server is overloaded and unable to produce the members list between the start and end of the chef-run.

**Pull request closed without merging**
