### PR TITLE
make sure the replica set name makes it to the config file

### PR DESCRIPTION
**Pull request by msaffitz**
Hackish fix for #169 to make sure that the replica set name makes it into the config for sharded replica set clusters.

### CODE REVIEW

**Comment by jamesonjlee** [comment]
couldn't something be a replicaset but not a shard?

**Comment by josephholsten** [comment]
yep, eg http://www.mongodb.com/blog/post/dont-let-your-standalone-mongodb-server-stand-alone

**Comment by josephholsten** [comment]
This would need to be reworked to play nice with #192. A direct translation would be something like:

``` ruby
if node['mongodb']['replicaset_name'].nil? && node.mongodb.is_shard && node.mongodb.is_replicaset
  node.default['mongodb']['config']['replSet'] = "rs_#{node['mongodb']['shard_name']}"
end
```

also, the first line probably should check `node['mongodb']['config']['replSet']` instead of `node['mongodb']['replicaset_name']` since the latter is deprecated.

It seems that this is attempting to reproduce the replicaset_name selection in [mongodb_instance](https://github.com/edelight/chef-mongodb/blob/master/definitions/mongodb.rb#L73-L95).

**Comment by josephholsten** [comment]
It seems the `replicaset_name` selection code is a nightmare. First off, I seem to have screwed up the shard side of the selection, which is fixed in #197.

After that patch, we're left with this selection code:

``` ruby
if new_resource.type == "shard"
  if new_resource.replicaset.nil?
    replicaset_name = nil
  else
    # for replicated shards we autogenerate the replicaset name for each shard
    replicaset_name = "rs_#{new_resource.replicaset['mongodb']['shard_name']}"
  end
else
  # if there is a predefined replicaset name we use it,
  # otherwise we try to generate one using 'rs_$SHARD_NAME'
  begin
    replicaset_name = new_resource.replicaset['mongodb']['replicaset_name']
  rescue
    replicaset_name = nil
  end
  if replicaset_name.nil?
    begin
      replicaset_name = "rs_#{new_resource.replicaset['mongodb']['shard_name']}"
    rescue
      replicaset_name = nil
    end
  end
end
```

But for all instances where we call `mongodb_instance` with a replicaset parameter, that replicaset is the node itself. Since I have no clue what it would mean to have the replicaset object be anything else, let's simplify to

``` ruby
new_resource.shard_name       = node['mongodb']['shard_name']
new_resource.replicaset_name  = node['mongodb']['replicaset_name']

if new_resource.type == "shard"
  if new_resource.replicaset.nil?
    replicaset_name = nil
  else
    # for replicated shards we autogenerate the replicaset name for each shard
    replicaset_name = "rs_#{new_resource.shard_name}"
  end
else
  # if there is a predefined replicaset name we use it,
  # otherwise we try to generate one using 'rs_$SHARD_NAME'
  begin
    replicaset_name = new_resource.replicaset_name
  rescue
    replicaset_name = nil
  end
  if replicaset_name.nil?
    begin
      replicaset_name = "rs_#{new_resource.shard_name}"
    rescue
      replicaset_name = nil
    end
  end
end
```

but this is kinda insane, since the whole think we're trying to ask is
whether we need a `replicaset_name` in the first place. So, assuming
#192, how about:

``` ruby
new_resource.shard_name       = node['mongodb']['shard_name']
new_resource.replicaset_name  = node['mongodb']['replicaset_name']
new_resource.is_replicaset    = node['mongodb']['is_replicaset']
new_resource.is_shard         = node['mongodb']['is_shard']

if new_resource.is_shard
  if new_resource.is_replicaset
    # for replicated shards we autogenerate the replicaset name for each shard
    replicaset_name = "rs_#{new_resource.shard_name}"
  else
    replicaset_name = nil
  end
else
  # if there is a predefined replicaset name we use it,
  # otherwise we try to generate one using 'rs_$SHARD_NAME'
  begin
    replicaset_name = new_resource.replicaset_name
  rescue
    replicaset_name = nil
  end
  if replicaset_name.nil?
    begin
      replicaset_name = "rs_#{new_resource.shard_name}"
    rescue
      replicaset_name = nil
    end
  end
end
```

Wow, I almost understand wtf is going on here! Still, it's awefully
complicated. This seems to actually embody the intent:

``` ruby
new_resource.shard_name       = node['mongodb']['shard_name']
new_resource.replicaset_name  = node['mongodb']['replicaset_name']
new_resource.is_replicaset    = node['mongodb']['is_replicaset']
new_resource.is_shard         = node['mongodb']['is_shard']

if new_resource.is_replicaset
  if new_resource.replicaset_name
    # trust a predefined replicaset name
    replicaset_name = new_resource.replicaset_name
  elsif new_resource.is_shard && new_resource.shard_name
    # for replicated shards we autogenerate
    # the replicaset name for each shard
    replicaset_name = "rs_#{new_resource.shard_name}"
  else
    # Well shoot, we don't have a predefined name and we aren't
    # really sharded. If we want backwards compatibity, this should be:
    #   replicaset_name = "rs_#{new_resource.shard_name}"
    # which with default values defaults to:
    #   replicaset_name = 'rs_default'
    # But using a non-default shard name when we're creating a default
    # replicaset name seems surprising to me and needlessly arbitrary.
    # So let's use the *default* default in this case:
    replicaset_name = 'rs_default'
else
  # not a replicaset, so no name
  replicaset_name = nil
end
```

Of course, this is _not_ perfectly backwards compatible, but it's also
nowhere near as crazy.

If we went with the above, then we probably want this patch to be:

``` ruby
if node['mongodb']['replicaset_name'].nil? && node.mongodb.is_replicaset
  if node.mongodb.is_shard
    node.default['mongodb']['config']['replSet'] = "rs_#{node['mongodb']['shard_name']}"
  else
    node.default['mongodb']['config']['replSet'] = 'rs_default'
  end
end
```

Thoughts?

**Comment by jspiewak** [comment]
The last block looks good to me.

**Comment by jspiewak** [comment]
Except "we're don't"
:)

**Comment by josephholsten** [comment]
fixed!

**Comment by josephholsten** [comment]
This is incorporated into #207 along with the cleanup I mentioned.

**Comment by jamesonjlee** [comment]
merged via 14b818f77b35646266c9dfcb460dcb93e3284664 then modified for new-style.

**Pull request closed without merging**
