### PR TITLE
disable gpgcheck according to mongodb docs

### PR DESCRIPTION
**Pull request by hifrank**
http://docs.mongodb.org/manual/tutorial/install-mongodb-on-red-hat-centos-or-fedora-linux/

### CODE REVIEW

**Comment by jamesonjlee** [comment]
doesn't this require that yum be >3.0.0?

**Comment by josephholsten** [comment]
on what platforms is yum < 3.0.0? I'll write a test.

**Comment by jamesonjlee** [comment]
@josephholsten I meant that the cookbook had to be >3.0.0

**Comment by josephholsten** [comment]
ah, sounds good. I prefer this approach to #190

**Pull request merged**
