### PR TITLE
Set open file limit for MongoDB process in Debian/Ubuntu to 64000

### PR DESCRIPTION
**Pull request by sam-realself**
- See http://docs.mongodb.org/manual/reference/ulimit/
- Fixes error: "Too many open files"

### CODE REVIEW

**Comment by josephholsten** [comment]
Why only on Debian & Ubuntu? Also, perhaps this value should be 65535, the highest it can be.

**Comment by josephholsten** [comment]
Oh, I see that's 10gen's recommended value. 64000 should be enough for anyone, then.

**Comment by sam-realself** [comment]
I only did it for Debian & Ubuntu because those were the only ones I am familiar with and tested on. I didn't want to assume that this method would be trouble-free for all distros that this cookbook supports.

**Comment by josephholsten** [comment]
:+1: if other distros need it, it's a good example.

**Comment by jamesonjlee** [comment]
I think this should be done via an LWRP provided by other cookbooks such as ulimit or sysctl.

**Comment by msaffitz** [comment]
I agree with @jamesonjlee, but in the meantime we have branch with this implemented for all platforms in the mongo config script.  Kind of hackish, but it works.

Branch at https://github.com/apptentive-engineering/chef-mongodb/tree/ulimits

Let me know if you want a pull request for this until it can properly be replaced by a LWRP

**Comment by mbbernstein** [comment]
Please check https://github.com/miah/chef-redis/pull/39

**Comment by josephholsten** [comment]
@jamesonjlee unfortunately, the ulimit cookbook approach will not work.

The ulimit cookbook's approach is using [`/etc/pam.d`](https://github.com/bmhatfield/chef-ulimit/blob/master/recipes/default.rb) and [`/etc/security/limits.d`](https://github.com/bmhatfield/chef-ulimit/blob/master/definitions/user_ulimit.rb) to automatically have the right settings when the daemon is started.

Our init script is running the daemon via `start-stop-daemon(8)`, which does not link with pam. Because of this, it does not respect `/etc/pam.d`, so it doesn't load `pam_limits.so`, so it doesn't evaluate the configs in `/etc/security/limits.d`.

Yes, this is a pain. Especially because many other ways of running the daemon do actually link with pam: `login(1)`, `su(1)`, `sudo(8)`. But generally process monitors don't respect pam, for example `upstart` and `runit(8)`.

Our init script is derived from upstream: [mongodb/mongo:debian/init.d](https://github.com/mongodb/mongo/blob/master/debian/init.d). If you'd like to rewrite the init script to not depend on start-stop-daemon, and get that in upstream, I'll gladly cheer you on. If you can get pam support into `start-stop-daemon(8)`, I will buy you many beverages. Because I would very much like to avoid this hack and help others avoid it as well.

But those solutions aren't really in the scope of this ticket, repo, or community. Le sigh.

**Comment by josephholsten** [comment]
@mbbernstein +1 to attributizing the value. As mongo is recommending 64000 as the default, we should too.

**Comment by ehershey** [comment]
Hi,

I'd love to make this easier. I'm working on some other changes to the
official mongod init script and if you have a good solution for this there,
I'll do what I can to get it accepted.

Here's our open JIRA if you want to watch/vote on/comment on the change.

https://jira.mongodb.org/browse/SERVER-6443

Ernie

**Comment by jamesonjlee** [comment]
then this seems reasonable, adding into 1.0.0 milestone.

**Comment by jamesonjlee** [comment]
@sam-realself could you also make the modification to the red-hat init script, so we can have this change all at once?

**Comment by jamesonjlee** [comment]
on ubuntu 10.04, because the default shell is dash `ulimit -u` spits an error (but doesn't affect anything, and by default the process limit is unlimited anyways)  otherwise it would have to be `ulimit -p` for dash

**Pull request merged**
