### PR TITLE
Promote mongodb cookbook into a first class cookbook repo

### PR DESCRIPTION
**Pull request by josephholsten**
It seems the broader cookbook has a consensus on single cookbook repos. With a fully self contained cookbook repo, we gain many options for modular reuse: librarian, knife-github-cookbooks, and git submodules. Opscode has broken up their repo this way also.

If we reorganize this way, we can also reuse the lovely "Installation" section from the popular https://github.com/fnichol/chef-rbenv cookbook.

I understand that this change imposes a burden on outstanding patches and pull requests. It's probably easiest to resolve those before applying this change. Especially in light of the new maintainers (see #31), I'm happy to wait a bit and rebase after the dust is settled.

### CODE REVIEW

**Comment by patcon** [comment]
++ on this idea overall :)

couple things:
- librarian already accommodates cookbooks in the current layout:
  
  ```
  cookbook "mongodb",
    :git => "https://github.com/edelight/chef-cookbooks.git",
    :path => "mongodb"
  ```
- If we're following semver, we can just bump the major version of the cookbook, and then we've done our due diligence in terms of protecting people downstream. Speaking of which, it be great if we could start tagging

I personally think it's best to get this over with sooner rather than later. Maybe we could pull in the no-brainer pull requests first, then go for it?

Cheers!

**Comment by miketheman** [comment]
So will this repo become "edelight/chef-mongodb" or "edelight/mongodb" ? If it only encompasses a single cookbook, that seems to be the way things are done.

**Comment by tobami** [comment]
We would certainly prefer `edelight/chef-mongodb`, as otherwise it is difficult to tell what the repo is about

**Comment by miketheman** [comment]
Ok, proposal:
- Merge in the changes to make the cookbook live as a first class citizen
- Rename the repository
- Update the [Community site](http://community.opscode.com/cookbooks/mongodb) to point to the correct path (@tobami or @thekorn)
- Publicize this via the chef-dev list (other places?)

What am I missing?

**Comment by josephholsten** [comment]
Perhaps after renaming, set up a placeholder README in case people end up here by mistake.

**Comment by patcon** [comment]
Good call on placeholder README.

Also:
- bump version to 1.0.0
- tag commit

**Comment by tobami** [comment]
@miketheman, @josephholsten good points.

I updated the [roadmap](https://github.com/edelight/chef-cookbooks/wiki/Roadmap) with your input

**Comment by patcon** [comment]
Thoughts on `chef-mongodb` vs `mongodb-cookbook`? I personally use `chef-blah`, but am realizing that this also seems to be the namespace for chef extensions and handlers on github:
http://rubygems.org/search?utf8=%E2%9C%93&query=chef-

Just thinking in terms of discoverability I suppose

**Comment by jamesonjlee** [comment]
+1 on this.

**Comment by tobami** [comment]
I am all for standardization and discoverability, but a sample of non-opscode cookbooks shows only chaos:
- [chef-graphite](https://github.com/cjAdvertising/chef-graphite)
- [cookbook-elasticsearch](https://github.com/karmi/cookbook-elasticsearch)
- [chef-redis](https://github.com/ctrabold/chef-redis)
- [chef-hadoop-cookbook](https://github.com/rweng/chef-hadoop-cookbook)

Do you have examples of well known cookbooks that follow a pattern?

**Comment by miketheman** [comment]
@tobami That's pretty true. But the nice thing is that all of those examples are 'first-class' cookbooks.

Since a cookbook repo isn't meant to be a rubygem (yet, at least), I'm in favor of `chef-mongodb`. @fnichol writes a fair amount of cookbooks, and names his `chef-<something>`.
This is also seen in https://github.com/heavywater

**Comment by tobami** [comment]
Settled then, we'll rename to `chef-mongodb`

**Comment by patcon** [comment]
> Since a cookbook repo isn't meant to be a rubygem (yet, at least), I'm in favor of `chef-mongodb`.

I think I was unclear on what I meant when I linked the rubygems sites. Was cryptically implied that most of those handlers hosted source on github, but it's all good. `chef-mongodb` it is :)

**Comment by josephholsten** [comment]
I personally follow @jtimberman's approach of `mongodb-cookbook` ala [jtimberman](https://github.com/search?q=%27-cookbook%27+username%3Ajtimberman&repo=&langOverride=&start_value=1&type=Repositories&language=).

But most of the source cookbooks in https://github.com/cookbooks use the `chef-mongodb`, like those of [fnichol](https://github.com/search?q=%27chef-%27+username%3Afnichol&repo=&langOverride=&start_value=1&type=Repositories&language=), [heavywater](https://github.com/search?q=%27chef-%27+username%3Aheavywater&repo=&langOverride=&start_value=1&type=Repositories&language=).

**Comment by miketheman** [comment]
It feels like consensus has been reached - I leave it to @tobami to merge, and rename the repo.

**Pull request merged**
