### PR TITLE
Force apt to update its source list

### PR DESCRIPTION
**Pull request by ehberg**
Might not be the best way to do this, but it works.

### CODE REVIEW

**Comment by miketheman** [comment]
It looks like this should be removed altogether, the apt_repository provider executes the update when there's something new to add. See here: https://github.com/opscode-cookbooks/apt/blob/master/providers/repository.rb#L68-102

**Comment by jamesonjlee** [comment]
should this be closed as will not be fixed?

**Comment by miketheman** [comment]
Well, the code should be removed.

**Comment by patcon** [comment]
Might want to add something like this to `metadata.rb` once that's removed:

```
depends "apt", "~> 1.4.4"
```

https://github.com/opscode-cookbooks/apt/blob/master/CHANGELOG.md#v144

**Comment by xofer** [comment]
The problem was fixed in the apt cookbook here: https://github.com/opscode-cookbooks/apt/pull/13
but not yet released.

**Pull request closed without merging**
