### PR TITLE
fixing redhad template to use mongodb_user attribute as the daemon user

### PR DESCRIPTION
**Pull request by shmuel-krakower**

### CODE REVIEW

**Comment by shmuel-krakower** [comment]
Hi,
First time I'm sending a pull request for this cookbook, please let me know if any more information is required, although it is pretty trivial fix.

**Comment by jamesonjlee** [comment]
looks like we need to do this for all init files, but then we need to track all the mongo accounts on all platforms :(.

@shmuel-krakower can you fill out the details (what is the default username for redhat install)

actually, https://github.com/edelight/chef-mongodb/blob/master/templates/default/redhat-mongodb.init.erb#L20 you should be able to set the user by setting `node['mongodb']['user'] = XYZ` does this not work?

**Comment by shmuel-krakower** [comment]
Hi
Red hat user is mongodb, the current user in the template, mongod, is wrong.

I have set the template variable, same as other variables are set and passed to the template.

I'm unsure if node attributes should be accessed from templates or not.

**Comment by shmuel-krakower** [comment]
@jamesonjlee  - thanks for the note, indeed daemon user is coming from sysconfig. I agree we should not merge my pull request as setting the appropriate node attribute is working.
I guess the only issue is with the default daemon for rhel defined in:
https://github.com/edelight/chef-mongodb/blob/master/attributes/default.rb#L79

Maybe that's only me - but the user I'm getting during the installation is mongodb and not mongod.

**Comment by jamesonjlee** [comment]
@shmuel-krakower are you installing from mongodb-org? also can you tell me your rhel/centos version?

**Comment by shmuel-krakower** [comment]
[root@build]# lsb_release -a
LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 6.4 (Santiago)
Release:        6.4
Codename:       Santiago

not sure regarding where the installation is coming from. Can you tell me how to check if I'm using mongodb-org?

**Comment by jamesonjlee** [comment]
ah sorry, I misread your question, I'll check if mongodb-org package makes a mongodb user or mongod user.

**Comment by jamesonjlee** [comment]
so I don't see how(?) that's possible from this cookbook, are you using the definitions separately from the cookbook?

**Comment by shmuel-krakower** [comment]
I just use the recipe with my wrapper recipe:
include_recipe "mongodb"

Other than that - for now I set the attributes I need from my wrapper cookbook:
##setting the right daemon user for mongodb on rhel
case node['platform_family']
when 'rhel'
  default['mongodb']['sysconfig']['DAEMONUSER'] = 'mongodb'
  default['mongodb']['sysconfig']['DAEMON_USER'] = 'mongodb'
  default['mongodb']['user'] = 'mongodb'
end

**Comment by jamesonjlee** [comment]
you need to modify the attributes _before_ you include the recipe.  Also for mongodb-org support you need to either
include the recipe `include_recipe 'mongodb-org-repo'`
or
change the `node['mongodb']['install_method'] = 'mongodb-org'`

**Pull request closed without merging**
