### PR TITLE
adds aws_ebs_volume recipe for creating EBS volume on EC2 instance

### PR DESCRIPTION
**Pull request by vitalis**
We use Amazon EC2 as infrastructure for our mongo setup. 
Amazon has a really good [guide](http://media.amazonwebservices.com/AWS_NoSQL_MongoDB.pdf) for setting up mongos on EC2.
They strongly recommend to use separate EBS volume for DB data storage.
I created a recipe according to this guide, hope it will be useful not only for me :)

### CODE REVIEW

**Comment by jwilf** [comment]
In my opinion this should not be merged. It is indeed good practice to use an EBS volume for data storage. However, creating EBS volumes is not done only for MongoDB, and also not everyone using this cookbook is using AWS. 

I would recommend you use this cookbook in conjuction with the existing Opscode AWS cookbook https://github.com/opscode-cookbooks/aws to create your EBS volume. Then in this cookbook set your dbpath to use the EBS volume created by the AWS cookbook.

**Comment by vitalis** [comment]
Hey @jwilf, the recipe is optional, and it simplifies MongoDB setup on EC2. And it's a bit more then creating EBS volume with Opscode AWS cookbook and setting dbpath

**Comment by jamesonjlee** [comment]
I think this one is a good doc reference, or a good include in a sample (business intelligence) recipe but not a part of the mongo cookbook itself.

**Comment by jamesonjlee** [comment]
@vitalis if you would like to add this into the docs (the repo wiki) or readme. I will gladly merge it, but otherwise, I would rather not see the cookbook get things tie it to specific providers.

**Pull request closed without merging**
