### PR TITLE
Convert mongodb_instance to resource

### PR DESCRIPTION
**Pull request by josephholsten**
DO NAE MERGE

still having a problem with notifications within the resource, which is why they are commented out.

Much more work should be done, especially to break apart the `mongod`, `shard`, `configserver` and `mongos` instance types into their own resources, and to really remove all access to node attributes.

### CODE REVIEW

**Comment by josephholsten** [comment]
this builds on the rebased #139

**Comment by josephholsten** [comment]
HOLY COW WE DID IT! Check the beauty that is:
- [recipes/default.rb](https://github.com/josephholsten/mongodb-cookbook/blob/6b7d191409d31e022c8de0a579c1eb0a36b3f58b/recipes/default.rb)
  [recipes/configserver.rb](https://github.com/josephholsten/mongodb-cookbook/blob/6b7d191409d31e022c8de0a579c1eb0a36b3f58b/recipes/configserver.rb)
- [recipes/mongos.rb](https://github.com/josephholsten/mongodb-cookbook/blob/6b7d191409d31e022c8de0a579c1eb0a36b3f58b/recipes/mongos.rb)
- [recipes/replicaset.rb](https://github.com/josephholsten/mongodb-cookbook/blob/6b7d191409d31e022c8de0a579c1eb0a36b3f58b/recipes/replicaset.rb)
- [recipes/shard.rb](https://github.com/josephholsten/mongodb-cookbook/blob/6b7d191409d31e022c8de0a579c1eb0a36b3f58b/recipes/shard.rb)

And all the weirdness that is mogos is contained in [libraries/mongos_instance.rb](https://github.com/josephholsten/mongodb-cookbook/blob/6b7d191409d31e022c8de0a579c1eb0a36b3f58b/libraries/mongos_instance.rb)

But the pièce de résistance is [libraries/instance.rb](https://github.com/josephholsten/mongodb-cookbook/blob/6b7d191409d31e022c8de0a579c1eb0a36b3f58b/libraries/instance.rb)

It's probably filled with bugs, and isn't documented at all, and I'm pretty sure there are bits which are jumping straight to node attributes instead of asking for things from the resource, but this is more or less what winning looks like.

**Comment by jspiewak** [comment]
These are awesome, significant changes. ETA on landing them? We had some work on a branch where we were fixing things up in the middle of December to get replica sets and sharding working for us. But we don't want to put more effort into that since it overlaps greatly with this, and is now a dead end.

We can start to help with bugs and documentation to push this forward if that would be useful.

**Comment by josephholsten** [comment]
This was really a spike to see where I'd like this to go. I've got to redo these changes in smaller pieces and get tests in. I may be ripping out poise from the provider side, it's resource collection block scoping breaks chefspec, which I still value.

I'll be doing that over the weekend. 

## 

http://josephholsten.com

**Comment by josephholsten** [comment]
I'd also like to investigate working well with the https://github.com/needle-cookbooks/chef-mongodb-composable mentioned in #166.

**Comment by jamesonjlee** [comment]
this is hot

**Comment by josephholsten** [comment]
I've updated this to integrate all the changes currently in master.

I think this will mostly depend on us actually having a test suite.

**Comment by kikicarbonell** [comment]
? what is the real state of this issue? it's ready to merge on master branch?

**Comment by devnore** [comment]
What is the status of this rewrite?

**Comment by jsirex** [comment]
https://github.com/poise/poise/issues/8

Also I have a few questions about new patch and whole mongodb cookbook.
Is it possible to:
1. Setup minimal sharded cluster for tests on single machine with 2 shards?
2. Put arbiter for replicaset of shard0 on server where replicaset of shard1 lives?
3. Does cookbook fully supports multiple instances of mongodb? If no, having HWRP for mongodb instance is useless, I think.

If it possible, could you please provide an example for these use-cases (runlist with/without attributes)

**Comment by runningman84** [comment]
any news here? Right now it seems to be impossible to setup a sharded cluster with the current cookbook :/

**Pull request closed without merging**
